name: doc_sys_pro
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.3 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  path_provider: ^2.0.2
  cupertino_icons: ^1.0.2
  cupertino_date_textbox: ^1.0.3
  google_sign_in: ^6.0.2
  get: ^4.6.5
  http: ^0.13.5
  image_picker: ^0.8.7+4
  folding_menu: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  hive_generator: ^2.0.0
  flutter_launcher_icons: ^0.12.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/doc_sys_pro_logo_1.png"

flutter:
  uses-material-design: true